name: client-order-portal
on:
  push: 
    branches: [develop]
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix: 
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use node.js ${{matrix.node-versions}}
        uses: actions/checkout@v2
        with: 
          node-version: ${{matrix.node-vsersion}}
      - run: npm i
      - run: npm run build --if-present 
      - run: npm test   

